<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NLog" Version="5.4.0" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.IO.Ports" Version="9.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AppConfiguration\AppConfiguration.csproj" />
    <ProjectReference Include="..\Utilities\Utilities.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Ag3466x_2_08">
      <HintPath>C:\ProgramData\Keysight\Command Expert\ScpiNetDrivers\Ag3466x_2_08.dll</HintPath>
    </Reference>
    <Reference Include="Keysight.CommandExpert.InstrumentAbstraction">
      <HintPath>..\Dll\Keysight.CommandExpert.InstrumentAbstraction.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
