name: Build .NET

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ["windows", "dotnet"]

    steps:
      - name: Allow PowerShell scripts
        run: Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
        shell: powershell

        - name: Manual checkout (safe for Gitea)
        run: |
            git init repo
            cd repo
        
            echo "Cloning from: http://192.168.1.91:3000/game_show_lda/AskMkiM.git"
            git remote add origin "http://192.168.1.91:3000/game_show_lda/AskMkiM.git"
            git fetch origin develop
            git checkout FETCH_HEAD
        shell: powershell


      - name: Restore dependencies
        run: dotnet restore repo\\AskMkiM.sln
        shell: powershell

      - name: Build
        run: dotnet build repo\\AskMkiM.sln --configuration Release
        shell: powershell

      - name: Test
        run: dotnet test repo\\AskMkiM.sln --no-build
        shell: powershell
