name: Build .NET

on:
  pull_request:
    branches:
      - "develop"
  workflow_dispatch:

jobs:
  build:
    runs-on: ["windows", "dotnet"]

    steps:
      - name: Allow PowerShell scripts
        run: Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
        shell: powershell

      - name: Checkout repository manually (Gitea PR Safe)
        run: |
          git init repo
          cd repo

          echo "Cloning from: ${{ gitea.repository.clone_url }}"
          git remote add origin "${{ gitea.repository.clone_url }}"

          echo "Fetching BASE (target) branch: ${{ gitea.base_ref }}"
          git fetch origin "${{ gitea.base_ref }}"

          echo "Fetching HEAD (source) branch: ${{ gitea.head_ref }}"
          git fetch origin "${{ gitea.head_ref }}"

          echo "Checkout HEAD of PR: ${{ gitea.head_ref }}"
          git checkout "${{ gitea.head_ref }}"
        shell: powershell

      - name: Restore dependencies
        run: dotnet restore repo\AskMkiM.sln

      - name: Build
        run: dotnet build repo\AskMkiM.sln --configuration Release

      - name: Test
        run: dotnet test repo\AskMkiM.sln --no-build
