//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Windows.WpfDocking.Windows.Docking {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI.Windows.WpfDocking.Windows.Docking.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Docking.
        /// </summary>
        internal static string Category_Docking {
            get {
                return ResourceManager.GetString("Category_Docking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Property Changed.
        /// </summary>
        internal static string Category_PropoertyChanged {
            get {
                return ResourceManager.GetString("Category_PropoertyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gets or sets the max number of undo unit in the undo/redo stack..
        /// </summary>
        internal static string Description_DockControl_MaxUndoLevel {
            get {
                return ResourceManager.GetString("Description_DockControl_MaxUndoLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The DockItems collection is not empty. Close all DockItem before calling DockControl.Load.
        /// </summary>
        internal static string Exception_DockControl_Load_DockItemsNotEmpty {
            get {
                return ResourceManager.GetString("Exception_DockControl_Load_DockItemsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can not redo when CanRedo is false or UndoUnitLevel is non-zero..
        /// </summary>
        internal static string Exception_DockControl_Redo_InvalidOperation {
            get {
                return ResourceManager.GetString("Exception_DockControl_Redo_InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can not undo when CanUndo is false or UndoUnitLevel is non-zero..
        /// </summary>
        internal static string Exception_DockControl_Undo_InvalidOperation {
            get {
                return ResourceManager.GetString("Exception_DockControl_Undo_InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot activate DockItem with DockPosition.Unknown..
        /// </summary>
        internal static string Exception_DockItem_Activate_InvalidDockPosition {
            get {
                return ResourceManager.GetString("Exception_DockItem_Activate_InvalidDockPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The ContextMenu is attached to DockItem already..
        /// </summary>
        internal static string Exception_DockItem_ContextMenuAttachedAlready {
            get {
                return ResourceManager.GetString("Exception_DockItem_ContextMenuAttachedAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The specified dock position is invalid..
        /// </summary>
        internal static string Exception_DockItem_Show_InvalidDockPosition {
            get {
                return ResourceManager.GetString("Exception_DockItem_Show_InvalidDockPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The source DockItem is attached to a different DockControl already..
        /// </summary>
        internal static string Exception_DockItem_VerifyShowParam_DifferentDockControl {
            get {
                return ResourceManager.GetString("Exception_DockItem_VerifyShowParam_DifferentDockControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The DockControl is not loaded..
        /// </summary>
        internal static string Exception_DockItem_VerifyShowParam_UnloadedDockControl {
            get {
                return ResourceManager.GetString("Exception_DockItem_VerifyShowParam_UnloadedDockControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid value to add. Value must be a non-null DockItem instance, which is not added to the collection..
        /// </summary>
        internal static string Exception_DockItemCollection_AddItem_InvalidValue {
            get {
                return ResourceManager.GetString("Exception_DockItemCollection_AddItem_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The dock value is invalid..
        /// </summary>
        internal static string Exception_DockTreeZOrder_InvalidDockValue {
            get {
                return ResourceManager.GetString("Exception_DockTreeZOrder_InvalidDockValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot host OverlayActivator multiple times..
        /// </summary>
        internal static string Exception_OverlayActivator_HostMultipleTimes {
            get {
                return ResourceManager.GetString("Exception_OverlayActivator_HostMultipleTimes", resourceCulture);
            }
        }
    }
}
