<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BaseOutputPath>C:\AskMkiM</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AppConfiguration\AppConfiguration.csproj" />
    <ProjectReference Include="..\DataBaseConfigruration\DataBaseConfiguration.csproj" />
    <ProjectReference Include="..\EventCore\EventCore.csproj" />
    <ProjectReference Include="..\NewCore\NewCore.csproj" />
    <ProjectReference Include="..\Utilities\Utilities.csproj" />
  </ItemGroup>

</Project>
