<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>

		<!-- 👇 Сборка в общую папку -->
		<OutputPath>D:\AskMkiM\Bin\</OutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>

		<!-- 🚫 Без вложенной папки win-x64 -->
		<RuntimeIdentifier></RuntimeIdentifier>
		<SelfContained>false</SelfContained>

		<!-- 👇 Для публикации (если будешь Publish делать) -->
		<PublishTrimmed>false</PublishTrimmed>
		<PublishDir>$(OutputPath)</PublishDir>
	</PropertyGroup>

	<!-- === Ссылки на проекты === -->
	<ItemGroup>
		<ProjectReference Include="..\DataBaseConfigruration\DataBaseConfiguration.csproj" />
		<ProjectReference Include="..\NewCore\NewCore.csproj" />
	</ItemGroup>

	<!-- === Контент для копирования === -->
	<ItemGroup>
		<Content Update="wwwroot\css\equipment.css">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Update="wwwroot\css\style.css">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Update="wwwroot\js\equipment.js">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Update="wwwroot\js\login.js">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

</Project>
